apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-blog-app
  labels:
    app: blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
    spec:
      initContainers:
        - image: docker.io/aokugel/test-django-web-app:latest
          name: blog-migration
          command: [ "python", "manage.py", "migrate"]
          envFrom:
          - configMapRef: 
              name: django-cm
          - secretRef: 
              name: django-secret
        - image: docker.io/aokugel/test-django-web-app:latest
          name: blog-collectstatic
          command: [ "python", "manage.py", "collectstatic", "--noinput"]
          envFrom:
          - configMapRef: 
              name: django-cm
          - secretRef: 
              name: django-secret
          - secretRef: 
              name: azure-blob-secret
      containers:
        - image: docker.io/aokugel/test-django-web-app:latest
          name: blog
          #Uncomment one of the below lines depending on if you want to use manage.py or gunicorn
          #command: [ "python", "manage.py", "runserver", "0.0.0.0:8000" ]
          command: ["gunicorn", "--bind", ":8000", "--workers", "3", "mysite.wsgi:application"]
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
          envFrom:
          - configMapRef: 
              name: django-cm
          - secretRef: 
              name: django-secret
              