# apiVersion: networking.k8s.io/v1beta1
# kind: Ingress
# metadata:
#   name: blog-ingress
#   annotations:
#     kubernetes.io/ingress.class: "nginx"
#     cert-manager.io/cluster-issuer: "letsencrypt-staging"
# spec:
#   tls:
#   - hosts:
#     - anthonykugel.com
#     secretName: blog-tls
#   rules:
#   - host: anthonykugel.com
#     http:
#       paths:
#       - backend:
#           serviceName: blog
#           servicePort: 8000