apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-postgres-db
  labels:
    app: postgres-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-db
  template:
    metadata:
      labels:
        app: postgres-db
    spec:
      containers:
        - image: postgres
          name: db
          envFrom:
            - configMapRef: 
                name: django-cm
