apiVersion: v1
kind: Service
metadata:
  name: postgres-db
  labels:
    app: postgres-db
spec:
  type: LoadBalancer
  selector:
    app: postgres-db
  ports:
    - port: 5432
      targetPort: 5432


# kind: Service
# metadata:
#   labels:
#     app: blog
#   name: django-blog-app
#   namespace: django-blog
# spec:
#   allocateLoadBalancerNodePorts: true
#   clusterIP: 10.111.162.48
#   clusterIPs:
#   - 10.111.162.48
#   externalTrafficPolicy: Cluster
#   internalTrafficPolicy: Cluster
#   ipFamilies:
#   - IPv4
#   ipFamilyPolicy: SingleStack
#   ports:
#   - nodePort: 31911
#     port: 8000
#     protocol: TCP
#     targetPort: 8000
#   selector:
#     app: blog
#   sessionAffinity: None
#   type: LoadBalancer
# status:
#   loadBalancer: {}