apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: django-pvc
spec:
  volumeName: pv0001
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  
